name: Run Image Correction

on:
  schedule:
    - cron: "7 */2 * * *"   # index.py 2時間おき(UTC)
    - cron: "5 0 1 * *"     # 毎月1日 00:05 (UTC) → 月次メンテ
  workflow_dispatch:
    inputs:
      target:
        description: "実行対象: auto=両方の判定, correction=補正のみ, monthly=月次のみ"
        required: false
        default: "auto"
        type: choice
        options: [auto, correction, monthly]

jobs:
  # ==== 毎時の画像補正 ====
  image_correction:
    # どのトリガで来たかで実行可否を分岐
    if: >
      (github.event_name == 'schedule' && github.event.schedule == '7 */2 * * *') ||
      (github.event_name == 'workflow_dispatch' && (inputs.target == 'auto' || inputs.target == 'correction'))
    runs-on: ubuntu-latest
    timeout-minutes: 25
    # ジョブ単位のコンカレンシー（補正ジョブ同士のみ排他）
    concurrency:
      group: image_correction
      cancel-in-progress: true
    permissions:
      contents: read
    env:
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
      DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
      DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements.txt"
      - run: python -m pip install --upgrade pip wheel
      - run: pip install -r requirements.txt
      - id: run_index
        run: |
          set -e
          python index.py 2>&1 | tee run.log
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-and-logs
          path: |
            run.log
            debug/**

  # ==== 月初のフォルダ作成／古いフォルダ削除 ====
  monthly_maintenance:
    if: >
      (github.event_name == 'schedule' && github.event.schedule == '5 0 1 * *') ||
      (github.event_name == 'workflow_dispatch' && (inputs.target == 'auto' || inputs.target == 'monthly'))
    runs-on: ubuntu-latest
    timeout-minutes: 20
    # ジョブ単位のコンカレンシー（月次ジョブ同士のみ排他）
    concurrency:
      group: monthly_maintenance
      cancel-in-progress: true
    permissions:
      contents: read
    env:
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
      DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
      DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements.txt"
      - run: python -m pip install --upgrade pip wheel
      - run: pip install -r requirements.txt
      - name: Create monthly folders
        run: python create_folder.py | tee create_folder.log
      - name: Remove old monthly folders
        run: python remove_folder.py | tee remove_folder.log
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monthly-maintenance-logs
          path: |
            create_folder.log
            remove_folder.log