name: Run Image Correction

on:
  schedule:
    - cron: "7 */2 * * *"   # # index.py 2時間おき(UTC)
    - cron: "5 0 1 * *"   # 毎月1日 00:05 (UTC) ≒ JST 09:05 → 月次メンテ
  workflow_dispatch:

# 実行中のものがあれば新しい実行をキャンセル（衝突防止）
concurrency:
  group: image_correction
  cancel-in-progress: true

jobs:
  # ==== 毎時の画像補正 ====
  image_correction:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: read
    env:
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
      DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
      DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip wheel

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the correction script (with retry)
        id: run_index
        run: |
          set -e
          python index.py 2>&1 | tee run.log

      - name: Upload debug artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-and-logs
          path: |
            run.log
            debug/**

  # ==== 月初のフォルダ作成／古いフォルダ削除 ====
  monthly_maintenance:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    env:
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
      DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
      DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip wheel

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create monthly folders
        run: python create_folder.py | tee create_folder.log

      - name: Remove old monthly folders
        run: python remove_folder.py | tee remove_folder.log

      - name: Upload maintenance logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monthly-maintenance-logs
          path: |
            create_folder.log
            remove_folder.log